name: Afdian Sync

on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # 
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  call-afdian-action:
    name: Call reusable afdian action workflow
    uses: LuoChu-NB2Dev/.github/.github/workflows/afdian-sync.yml@master
    permissions:
      contents: write
      pull-requests: write
    secrets:
      AFDIAN_USERID: ${{ secrets.AFDIAN_USERID }}
      AFDIAN_TOKEN: ${{ secrets.AFDIAN_TOKEN }}