name: Test Release

on:
  push:
    tags:
      - 't*'

jobs:
  call-template:
    name: Call reusable template test release
    uses: LuoChu-NB2Dev/.github/.github/workflows/testrelease.yml@master
    permissions:
      contents: write
      pull-requests: write

  publish-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: call-template
    environment:
      name: testpypi
      url: https://test.pypi.orgp/nonebot-plugin-template/
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download dist artifacts from reusable workflow
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: ./dist

      - name: List downloaded files
        run: ls -l ./dist

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
